catalogMode: prefer
cleanupUnusedCatalogs: true

publicHoistPattern:
  - "@typescript/*"

shellEmulator: true

catalog:
  "@clack/prompts": ^0.11.0
  "@isentinel/eslint-config": ^5.0.0-beta.1
  "@isentinel/tsconfig": ^1.2.0
  "@types/node": ^25.0.10
  "@typescript/native-preview": 7.0.0-dev.20260212.1
  "@vitest/coverage-v8": ^4.0.18
  "@vitest/eslint-plugin": ^1.6.9
  better-typescript-lib: ^2.12.0
  eslint: ^9.39.2
  eslint-plugin-n: ^17.23.2
  eslint-plugin-pnpm: ^1.5.0
  eslint_d: ^14.3.0
  file-entry-cache: ^11.1.2
  jiti: ^2.6.1
  lint-staged: ^15.5.1
  madge: ^8.0.0
  simple-git-hooks: ^2.11.1
  typescript: ^5.9.3
  vitest: ^4.0.18

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - unrs-resolver
