catalogMode: prefer
cleanupUnusedCatalogs: true
shellEmulator: true

catalog:
  "@clack/prompts": ^0.11.0
  "@isentinel/eslint-config": ^4.7.0
  "@isentinel/tsconfig": ^1.2.0
  "@types/node": ^25.0.10
  eslint: ^9.39.2
  eslint-plugin-n: ^17.23.2
  eslint-plugin-pnpm: ^1.5.0
  jiti: ^2.6.1
  lint-staged: ^15.5.1
  simple-git-hooks: ^2.11.1
  typescript: ^5.9.3

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - unrs-resolver
